let posts = [{
    'author-img': '<img class="author-img" src="img/blankprofil.png">',
    'author': 'Landschaftsfotograf 1337',
    'location': '',
    'post-img': '<img class="post-img" src="img/post1.jpg">',
    'likes': 123,
    'text': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo, nobis incidunt? Quidem ratione necessitatibus repellat perspiciatis, voluptatem nam adipisci quis enim doloribus rem reprehenderit placeat labore magni minima vel quibusdam!',
    'comments': [],
    'datum': 3,
},
{
    'author-img': '<img class="author-img" src="img/blankprofil.png">',
    'author': 'Urlauber 1337',
    'location': '<img class="location-pin" src="img/logo/pin-8-32.jpg">Tokyo',
    'post-img': '<img class="post-img" src="img/post2.jpg">',
    'likes': 1234,
    'text': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo, nobis incidunt? Quidem ratione necessitatibus repellat perspiciatis, voluptatem nam adipisci quis enim doloribus rem reprehenderit placeat labore magni minima vel quibusdam!',
    'comments': [],
    'datum': 15,
},
{
    'author-img': '<img class="author-img" src="img/blankprofil.png">',
    'author': 'Rennfahrer 1337',
    'location': '<img class="location-pin" src="img/logo/pin-8-32.jpg">Hockenheimring',
    'post-img': '<img class="post-img" src="img/post3.jpg">',
    'likes': 321,
    'text': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo, nobis incidunt? Quidem ratione necessitatibus repellat perspiciatis, voluptatem nam adipisci quis enim doloribus rem reprehenderit placeat labore magni minima vel quibusdam!',
    'comments': [],
    'datum': 19,
},
{
    'author-img': '<img class="author-img" src="img/blankprofil.png">',
    'author': 'Taucher 1337',
    'location': '<img class="location-pin" src="img/logo/pin-8-32.jpg">Ägypten Hurghada',
    'post-img': '<img class="post-img" src="img/post4.jpg">',
    'likes': 4321,
    'text': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo, nobis incidunt? Quidem ratione necessitatibus repellat perspiciatis, voluptatem nam adipisci quis enim doloribus rem reprehenderit placeat labore magni minima vel quibusdam!',
    'comments': [],
    'datum': 23,
},
{
    'author-img': '<img class="author-img" src="img/blankprofil.png">',
    'author': 'Rocker 1337',
    'location': '<img class="location-pin" src="img/logo/pin-8-32.jpg">Konzerthalle XY',
    'post-img': '<img class="post-img" src="img/post5.jpg">',
    'likes': 1,
    'text': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo, nobis incidunt? Quidem ratione necessitatibus repellat perspiciatis, voluptatem nam adipisci quis enim doloribus rem reprehenderit placeat labore magni minima vel quibusdam!',
    'comments': [],
    'datum': 36,
},
];